export const GET_PRODUCT_PAGE_REQUEST = 'GET_PRODUCT_PAGE_REQUEST'
export const GET_PRODUCT_PAGE_SUCCESS = 'GET_PRODUCT_PAGE_SUCCESS'
export const GET_PRODUCT_PAGE_FAILURE = 'GET_PRODUCT_PAGE_FAILURE'
