export const GET_ALL_CATEGORIES_REQUEST = 'GET_ALL_CATEGORIES_REQUEST'
export const GET_ALL_CATEGORIES_SUCCESS = 'GET_ALL_CATEGORIES_SUCCESSS'
export const GET_ALL_CATEGORIES_FAIL = 'GET_ALL_CATEGORIES_FAIL'

export const ADD_NEW_CATEGORY_REQUEST = 'ADD_NEW_CATEGORY_REQUEST'
export const ADD_NEW_CATEGORY_SUCCESS = 'ADD_NEW_CATEGORY_REQUEST'
export const ADD_NEW_CATEGORY_FAIL = 'ADD_NEW_CATEGORY_FAIL'
