export const GET_ALL_INITIAL_DATA_REQUEST = 'GET_ALL_INITIAL_DATA_REQUEST'
export const GET_ALL_INITIAL_DATA_SUCCESS = 'GET_ALL_INITIAL_DATA_SUCCESS'
export const GET_ALL_INITIAL_DATA_FAILURE = 'GET_ALL_INITIAL_DATA_FAILURE'
