export const GET_PRODUCTS_BY_SLUG = 'GET_PRODUCTS_BY_SLUG'

export const GET_PRODUCT_PAGE_REQUEST = 'GET_PRODUCT_PAGE_REQUEST'
export const GET_PRODUCT_PAGE_SUCCESS = 'GET_PRODUCT_PAGE_SUCCESS'
export const GET_PRODUCT_PAGE_FAILURE = 'GET_PRODUCT_PAGE_FAILURE'

export const GET_PRODUCT_DETAILS_BY_ID_REQUEST =
  'GET_PRODUCT_DETAILS_BY_ID_REQUEST'
export const GET_PRODUCT_DETAILS_BY_ID_SUCCESS =
  'GET_PRODUCT_DETAILS_BY_ID_SUCCESS'
export const GET_PRODUCT_DETAILS_BY_ID_FAILURE =
  'GET_PRODUCT_DETAILS_BY_ID_FAILURE'
